using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading;

namespace Frends.SMTP.SendEmail
{
    /// <summary>
    /// SMTP Task.
    /// </summary>
    public static class SMTP
    {
        /// <summary>
        /// Frends Task for sending emails with optional attachments using SMTP protocol.
        /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.SMTP.SendEmail)
        /// <param name="message">Input parameters</param>
        /// <param name="attachments">Attachment parameters</param>
        /// <param name="SMTPSettings">Options parameters</param>
        /// <param name="cancellationToken">Token generated by Frends to stop this task.</param>
        /// </summary>
        /// <returns> Object { bool EmailSent, string StatusString } </returns>
        public static Output SendEmail([PropertyTab] Input message, [PropertyTab] Attachment[] attachments, [PropertyTab] Options SMTPSettings, CancellationToken cancellationToken)
        {
            var output = new Output();

            using (var client = InitializeSmtpClient(SMTPSettings))
            {
                using (var mail = InitializeMailMessage(message))
                {
                    if (attachments != null)
                        foreach (var attachment in attachments)
                        {
                            if (attachment.AttachmentType == AttachmentType.FileAttachment)
                            {
                                ICollection<string> allAttachmentFilePaths = GetAttachmentFiles(attachment.FilePath);

                                if (attachment.ThrowExceptionIfAttachmentNotFound && allAttachmentFilePaths.Count == 0)
                                    throw new FileNotFoundException(string.Format("The given filepath \"{0}\" had no matching files", attachment.FilePath), attachment.FilePath);

                                if (allAttachmentFilePaths.Count == 0 && !attachment.SendIfNoAttachmentsFound)
                                {
                                    output.StatusString = string.Format("No attachments found matching path \"{0}\". No email sent.", attachment.FilePath);
                                    output.EmailSent = false;
                                    return output;
                                }

                                foreach (var fp in allAttachmentFilePaths)
                                    mail.Attachments.Add(new System.Net.Mail.Attachment(fp));
                            }

                            if (attachment.AttachmentType == AttachmentType.AttachmentFromString && !string.IsNullOrEmpty(attachment.StringAttachment.FileContent))
                                mail.Attachments.Add(System.Net.Mail.Attachment.CreateAttachmentFromString(attachment.StringAttachment.FileContent, attachment.StringAttachment.FileName));

                        }

                    cancellationToken.ThrowIfCancellationRequested();

                    client.Send(mail);

                    output.EmailSent = true;
                    output.StatusString = string.Format("Email sent to: {0}", mail.To.ToString());

                    return output;
                }
            }
        }

        private static SmtpClient InitializeSmtpClient(Options settings)
        {
            var smtpClient = new SmtpClient
            {
                Port = settings.Port,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = settings.UseWindowsAuthentication,
                EnableSsl = settings.UseSsl,
                Host = settings.SMTPServer
            };

            if (!settings.UseWindowsAuthentication && !string.IsNullOrEmpty(settings.UserName))
                smtpClient.Credentials = new NetworkCredential(settings.UserName, settings.Password);

            return smtpClient;
        }

        private static MailMessage InitializeMailMessage(Input input)
        {
            //split recipients, either by comma or semicolon
            var separators = new[] { ',', ';' };

            string[] recipients = input.To.Split(separators, StringSplitOptions.RemoveEmptyEntries);
            string[] ccRecipients = input.Cc.Split(separators, StringSplitOptions.RemoveEmptyEntries);
            string[] bccRecipients = input.Bcc.Split(separators, StringSplitOptions.RemoveEmptyEntries);

            //Create mail object
            var mail = new MailMessage()
            {
                From = new MailAddress(input.From, input.SenderName),
                Subject = input.Subject,
                Body = input.Message,
                IsBodyHtml = input.IsMessageHtml
            };

            //Add recipients
            foreach (var recipientAddress in recipients)
                mail.To.Add(recipientAddress);

            //Add CC recipients
            foreach (var ccRecipient in ccRecipients)
                mail.CC.Add(ccRecipient);

            //Add BCC recipients
            foreach (var bccRecipient in bccRecipients)
                mail.Bcc.Add(bccRecipient);

            //Set message encoding
            Encoding encoding = Encoding.GetEncoding(input.MessageEncoding);

            mail.BodyEncoding = encoding;
            mail.SubjectEncoding = encoding;

            return mail;
        }

        private static ICollection<string> GetAttachmentFiles(string filePath)
        {
            string folder = Path.GetDirectoryName(filePath);
            string fileMask = Path.GetFileName(filePath) != "" ? Path.GetFileName(filePath) : "*";

            string[] filePaths = Directory.GetFiles(folder, fileMask);

            return filePaths;
        }
    }
}