name: BuildAndTestOnEveryPush.yml

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      env_var_name_1: SMTP_PASSWORD
    secrets:
      env_var_value_1: ${{ secrets.SMTP_PASSWORD }}
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
