name: Frends.Smtp.SendEmail Main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.Smtp.SendEmail/**'
      - 'Frends.Smtp.SendEmail.Tests/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      env_var_name_1: SMTP_PASSWORD
      workdir: Frends.Smtp.SendEmail
    secrets:
      env_var_value_1: ${{ secrets.SMTP_PASSWORD }}
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      