name: Frends.SMTP.SendEmail Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.SMTP.SendEmail/**'
      - 'Frends.SMTP.SendEmail.Tests/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      env_var_name_1: SMTP_PASSWORD
      workdir: Frends.SMTP.SendEmail
    secrets:
      env_var_value_1: ${{ secrets.SMTP_PASSWORD }}
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      